test ci 308

diff --git a/.github/workflows/tf-ci.yml b/.github/workflows/tf-ci.yml
--- a/.github/workflows/tf-ci.yml
+++ b/.github/workflows/tf-ci.yml
@@ -75,11 +75,11 @@ jobs:
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
 
-    - name: 'Run Azure CLI commands'
-      run: |
-          az account show
-          az group list
-          pwd 
+    #- name: 'Run Azure CLI commands'
+    #  run: |
+    #      az account show
+    #      az group list
+    #      pwd 
 
     - name: Checkout
       uses: actions/checkout@v2
@@ -155,36 +155,38 @@ jobs:
       working-directory: ${{ github.workspace }}
 
     - name : Get EclWatch IP
-      if: always()
+      #if: always()
       run: |
+        ls -l ~/.kube/config
+        helm list
         kubectl get nodes
         kubectl get pod
-    ##    sleep 60
-    ##    failed_pods=$(kubectl get pod | grep -v "1/1" | grep -v "2/2" | grep -v "NAME" || true) &&
-    ##    if [ "$failed_pods" != "" ]; then
-    ##       echo "Pods not ready:"
-    ##       echo "$failed_pods"
-    ##       exit 1
-    ##    end 
-    ##    #eclwatch_ip=$(kubectl get service | grep "^eclwatch" | sed "s/\(\s\)\+/ /g" | cut -d' ' -f 4)
-    ##    eclwatch_ip=$(kubectl get svc --field-selector metadata.name=eclwatch | awk 'NR==2 {print $4}')
-    ##    echo "ECLWATCH_IP=${eclwatch_ip} >> $GITHUB_ENV
-    ##    echo "ECLWATCH_IP: ${{ env.ECLWATCH }}"
+        eclwatch_ip=$(kubectl get svc --field-selector metadata.name=eclwatch | awk 'NR==2 {print $4}')
+        echo "ECLWATCH_IP=${eclwatch_ip} >> $GITHUB_ENV
+        echo "ECLWATCH_IP: ${{ env.ECLWATCH }}"
+    #    failed_pods=$(kubectl get pod | grep -v "1/1" | grep -v "2/2" | grep -v "NAME" || true) &&
+    #    if [ "$failed_pods" != "" ]; then
+    #       echo "Pods not ready:"
+    #       echo "$failed_pods"
+    #       exit 1
+    #    end 
+    #    #eclwatch_ip=$(kubectl get service | grep "^eclwatch" | sed "s/\(\s\)\+/ /g" | cut -d' ' -f 4)
         
-    ##- name: Change test directory permission
-    ##  run: |
-    #    #echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
-    #    #echo "github.workspace: ${{ github.workspace }} "
-    #    #chmod 777 ${{ github.workspace }}/devops/test/basic
+        
+    - name: Change test directory permission
+      run: |
+        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
+        echo "github.workspace: ${{ github.workspace }} "
+        chmod 777 ${{ github.workspace }}/devops/test/basic
 
-    ##- name: Run ECL Test
-    ##  uses: addnab/docker-run-action@v3
-    ##  with:
-    ##    image: hpccsystems/platform-core:latest
-    ##    options: --rm -v ${{ github.workspace }}/devops/test/basic:/basic-test
-    ##    run: |
-    ##      #/opt/HPCCSystems/bin/ecl run  -s ${{ env.ECLWATCH_IP }} hthor /basic-test/simple.ecl
-    ##      /basic-test/run.sh ${{ env.ECLWATCH_IP }}
+    - name: Run ECL Test
+      uses: addnab/docker-run-action@v3
+      with:
+        image: hpccsystems/platform-core:latest
+        options: --rm -v ${{ github.workspace }}/devops/test/basic:/basic-test
+        run: |
+         /basic-test/run.sh ${{ env.ECLWATCH_IP }}
+         #/opt/HPCCSystems/bin/ecl run  -s ${{ env.ECLWATCH_IP }} hthor /basic-test/simple.ecl
 
     - name: Destroy HPCC-Platform  Terraform
       if: always()
