test ci 290

diff --git a/.github/workflows/tf-ci.yml b/.github/workflows/tf-ci.yml
--- a/.github/workflows/tf-ci.yml
+++ b/.github/workflows/tf-ci.yml
@@ -6,8 +6,8 @@ on:
     - 'az-devops'
 
 permissions:
-        contents: 'read'
-        id-token: 'write'
+        contents: read
+        id-token: write
 
 jobs:    
 
@@ -68,130 +68,136 @@ jobs:
 
     
 
-    #- name: 'Az CLI login'
-    #  uses: azure/login@v1
-    #  with:
-    #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
-    #    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-    #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
-        
-    - name: Checkout
-      uses: actions/checkout@v2
+    - name: 'Az CLI login'
+      uses: azure/login@v1
+      with:
+        client-id: ${{ secrets.AZURE_CLIENT_ID }}
+        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
-      #id: setup-terraform
-
-    #- name: Setup Kubectl
-    #  uses: azure/setup-kubectl@v3
-    #  #id: setup-kubectl
-
-    - name: Setup kubelgoin
+    - name: 'Run Azure CLI commands'
       run: |
-        sudo az aks install-cli
+          az account show
+          az group list
+          pwd 
 
+    #- name: Checkout
+    #  uses: actions/checkout@v2
 
-    - name: Prepare VNet Terraform files
-      run: |
-        cp ${{ github.workspace }}/devops/terraform/vnet-versions.tf \
-         ${{ github.workspace }}/modules/virtual_network/versions.tf
-        cp ${{ github.workspace }}/devops/terraform/vnet-providers.tf \
-         ${{ github.workspace }}/modules/virtual_network/providers.tf
-        cp ${{ github.workspace }}/devops/terraform/vnet.tfvars \
-         ${{ github.workspace }}/modules/virtual_network/admin.auto.tfvars
+    #- name: Setup Terraform
+    #  uses: hashicorp/setup-terraform@v2
+    #  #id: setup-terraform
 
-    - name: Initialize VNet erraform
-      run: terraform init
-      working-directory: ${{ github.workspace }}/modules/virtual_network
+    ##- name: Setup Kubectl
+    ##  uses: azure/setup-kubectl@v3
+    ##  #id: setup-kubectl
 
-    - name: Apply VNet Terraform
-      #run: terraform apply  -auto-approve
-      run: terraform apply -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}" }' -auto-approve
-      working-directory: ${{ github.workspace }}/modules/virtual_network
-
-
-    - name: Prepare SC Terraform files
-      run: |
-        cp ${{ github.workspace }}/devops/terraform/sc-versions.tf \
-         ${{ github.workspace }}/modules/storage_account/versions.tf
-        cp ${{ github.workspace }}/devops/terraform/sc-providers.tf \
-         ${{ github.workspace }}/modules/storage_account/providers.tf
-        cp ${{ github.workspace }}/devops/terraform/sc.tfvars \
-         ${{ github.workspace }}/modules/storage_account/admin.auto.tfvars
-
-    - name: Initialize SC Terraform
-      run: terraform init
-      working-directory: ${{ github.workspace }}/modules/storage_account
-
-    - name: Apply SC Terraform
-      #run: terraform apply  -auto-approve
-      run: terraform apply -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}" }' -auto-approve
-      working-directory: ${{ github.workspace }}/modules/storage_account
-
-    - name: Prepare HPCC Terraform files
-      run: |
-        cp ${{ github.workspace }}/devops/terraform/hpcc-versions.tf \
-         ${{ github.workspace }}/versions.tf
-        cp ${{ github.workspace }}/devops/terraform/hpcc-providers.tf \
-         ${{ github.workspace }}/providers.tf
-        cp ${{ github.workspace }}/devops/terraform/hpcc.tfvars \
-         ${{ github.workspace }}/admin.auto.tfvars
-        cp ${{ github.workspace }}/devops/terraform/hpcc-locals.tf \
-         ${{ github.workspace }}/locals.tf
-
-    - name: Initialize HPCC-Platform Terraform
-      run: terraform init
-      working-directory: ${{ github.workspace }}
-
-    - name: Apply HPCC-Platform Terraform
-      #run: terraform apply  -auto-approve
-      run: terraform apply -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}", "server_id":"${{ secrets.SERVER_ID }}","object_id":"${{ secrets.OBJECT_ID }}"  }' -auto-approve
-      working-directory: ${{ github.workspace }}
-
-    - name : Get EclWatch IP
-      run: |
-        kubectl get pod
-    #    sleep 60
-    #    failed_pods=$(kubectl get pod | grep -v "1/1" | grep -v "2/2" | grep -v "NAME" || true) &&
-    #    if [ "$failed_pods" != "" ]; then
-    #       echo "Pods not ready:"
-    #       echo "$failed_pods"
-    #       exit 1
-    #    end 
-    #    #eclwatch_ip=$(kubectl get service | grep "^eclwatch" | sed "s/\(\s\)\+/ /g" | cut -d' ' -f 4)
-    #    eclwatch_ip=$(kubectl get svc --field-selector metadata.name=eclwatch | awk 'NR==2 {print $4}')
-    #    echo "ECLWATCH_IP=${eclwatch_ip} >> $GITHUB_ENV
-    #    echo "ECLWATCH_IP: ${{ env.ECLWATCH }}"
-        
-    #- name: Change test directory permission
+    #- name: Setup kubelgoin
     #  run: |
-        #echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
-        #echo "github.workspace: ${{ github.workspace }} "
-        #chmod 777 ${{ github.workspace }}/devops/test/basic
+    #    sudo az aks install-cli
 
-    #- name: Run ECL Test
-    #  uses: addnab/docker-run-action@v3
-    #  with:
-    #    image: hpccsystems/platform-core:latest
-    #    options: --rm -v ${{ github.workspace }}/devops/test/basic:/basic-test
-    #    run: |
-    #      #/opt/HPCCSystems/bin/ecl run  -s ${{ env.ECLWATCH_IP }} hthor /basic-test/simple.ecl
-    #      /basic-test/run.sh ${{ env.ECLWATCH_IP }}
 
-    - name: Destroy HPCC-Platform  Terraform
-      if: always()
-      #run: terraform destroy -auto-approve
-      run: terraform destroy -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}", "server_id":"${{ secrets.SERVER_ID }}","object_id":"${{ secrets.OBJECT_ID }}" }' -auto-approve
-      working-directory: ${{ github.workspace }}
+    #- name: Prepare VNet Terraform files
+    #  run: |
+    #    cp ${{ github.workspace }}/devops/terraform/vnet-versions.tf \
+    #     ${{ github.workspace }}/modules/virtual_network/versions.tf
+    #    cp ${{ github.workspace }}/devops/terraform/vnet-providers.tf \
+    #     ${{ github.workspace }}/modules/virtual_network/providers.tf
+    #    cp ${{ github.workspace }}/devops/terraform/vnet.tfvars \
+    #     ${{ github.workspace }}/modules/virtual_network/admin.auto.tfvars
 
-    - name: Destroy SC Terraform
-      if: always()
-      #run: terraform destroy -auto-approve
-      run: terraform destroy -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}" }' -auto-approve
-      working-directory: ${{ github.workspace }}/modules/storage_account
+    #- name: Initialize VNet erraform
+    #  run: terraform init
+    #  working-directory: ${{ github.workspace }}/modules/virtual_network
 
-    - name: Destroy VNet Terraform
-      if: always()
-      #run: terraform destroy -auto-approve
-      run: terraform destroy -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}" }' -auto-approve
-      working-directory: ${{ github.workspace }}/modules/virtual_network
+    #- name: Apply VNet Terraform
+    #  #run: terraform apply  -auto-approve
+    #  run: terraform apply -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}" }' -auto-approve
+    #  working-directory: ${{ github.workspace }}/modules/virtual_network
+
+
+    #- name: Prepare SC Terraform files
+    #  run: |
+    #    cp ${{ github.workspace }}/devops/terraform/sc-versions.tf \
+    #     ${{ github.workspace }}/modules/storage_account/versions.tf
+    #    cp ${{ github.workspace }}/devops/terraform/sc-providers.tf \
+    #     ${{ github.workspace }}/modules/storage_account/providers.tf
+    #    cp ${{ github.workspace }}/devops/terraform/sc.tfvars \
+    #     ${{ github.workspace }}/modules/storage_account/admin.auto.tfvars
+
+    #- name: Initialize SC Terraform
+    #  run: terraform init
+    #  working-directory: ${{ github.workspace }}/modules/storage_account
+
+    #- name: Apply SC Terraform
+    #  #run: terraform apply  -auto-approve
+    #  run: terraform apply -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}" }' -auto-approve
+    #  working-directory: ${{ github.workspace }}/modules/storage_account
+
+    #- name: Prepare HPCC Terraform files
+    #  run: |
+    #    cp ${{ github.workspace }}/devops/terraform/hpcc-versions.tf \
+    #     ${{ github.workspace }}/versions.tf
+    #    cp ${{ github.workspace }}/devops/terraform/hpcc-providers.tf \
+    #     ${{ github.workspace }}/providers.tf
+    #    cp ${{ github.workspace }}/devops/terraform/hpcc.tfvars \
+    #     ${{ github.workspace }}/admin.auto.tfvars
+    #    cp ${{ github.workspace }}/devops/terraform/hpcc-locals.tf \
+    #     ${{ github.workspace }}/locals.tf
+
+    #- name: Initialize HPCC-Platform Terraform
+    #  run: terraform init
+    #  working-directory: ${{ github.workspace }}
+
+    #- name: Apply HPCC-Platform Terraform
+    #  #run: terraform apply  -auto-approve
+    #  run: terraform apply -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}", "server_id":"${{ secrets.SERVER_ID }}","object_id":"${{ secrets.OBJECT_ID }}"  }' -auto-approve
+    #  working-directory: ${{ github.workspace }}
+
+    #- name : Get EclWatch IP
+    #  run: |
+    #    kubectl get pod
+    ##    sleep 60
+    ##    failed_pods=$(kubectl get pod | grep -v "1/1" | grep -v "2/2" | grep -v "NAME" || true) &&
+    ##    if [ "$failed_pods" != "" ]; then
+    ##       echo "Pods not ready:"
+    ##       echo "$failed_pods"
+    ##       exit 1
+    ##    end 
+    ##    #eclwatch_ip=$(kubectl get service | grep "^eclwatch" | sed "s/\(\s\)\+/ /g" | cut -d' ' -f 4)
+    ##    eclwatch_ip=$(kubectl get svc --field-selector metadata.name=eclwatch | awk 'NR==2 {print $4}')
+    ##    echo "ECLWATCH_IP=${eclwatch_ip} >> $GITHUB_ENV
+    ##    echo "ECLWATCH_IP: ${{ env.ECLWATCH }}"
+        
+    ##- name: Change test directory permission
+    ##  run: |
+    #    #echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
+    #    #echo "github.workspace: ${{ github.workspace }} "
+    #    #chmod 777 ${{ github.workspace }}/devops/test/basic
+
+    ##- name: Run ECL Test
+    ##  uses: addnab/docker-run-action@v3
+    ##  with:
+    ##    image: hpccsystems/platform-core:latest
+    ##    options: --rm -v ${{ github.workspace }}/devops/test/basic:/basic-test
+    ##    run: |
+    ##      #/opt/HPCCSystems/bin/ecl run  -s ${{ env.ECLWATCH_IP }} hthor /basic-test/simple.ecl
+    ##      /basic-test/run.sh ${{ env.ECLWATCH_IP }}
+
+    #- name: Destroy HPCC-Platform  Terraform
+    #  if: always()
+    #  #run: terraform destroy -auto-approve
+    #  run: terraform destroy -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}", "server_id":"${{ secrets.SERVER_ID }}","object_id":"${{ secrets.OBJECT_ID }}" }' -auto-approve
+    #  working-directory: ${{ github.workspace }}
+
+    #- name: Destroy SC Terraform
+    #  if: always()
+    #  #run: terraform destroy -auto-approve
+    #  run: terraform destroy -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}" }' -auto-approve
+    #  working-directory: ${{ github.workspace }}/modules/storage_account
+
+    #- name: Destroy VNet Terraform
+    #  if: always()
+    #  #run: terraform destroy -auto-approve
+    #  run: terraform destroy -var='azure={ "tenant_id":"${{ secrets.AZURE_TENANT_ID }}", "subscription_id":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "client_id":"${{ secrets.AZURE_CLIENT_ID }}", "client_secret":"${{ secrets.SERVICE_PRINCIPAL_VALUE }}" }' -auto-approve
+    #  working-directory: ${{ github.workspace }}/modules/virtual_network
